name: CI

on:
  push:
    branches:
      - "main"

env:
  GHCR_TAG: ghcr.io/${{ github.repository }}
  PROJECT_ID: platinum-tube-307016
  GAR_REGION: europe-west1
  GAR_REPOSITORY: docker-repository
  GAR_TAG: europe-west1-docker.pkg.dev/platinum-tube-307016/docker-repository/${{ github.repository }}

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          token_format: "access_token"
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Login to Google Artifact registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GAR_REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and test
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: ${{ env.GHCR_TAG }}:test

      - name: Test
        run: docker run --rm -e INTEGRATION_TEST=true ${{ env.GHCR_TAG }}:test deno test -A

      - name: Build and push to registries
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ env.GHCR_TAG }}:latest 
            ${{ env.GAR_TAG }}:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          image: ${{ env.GAR_TAG }}:latest
          service: font-packager
          region: ${{ env.GAR_REGION }}
